openapi: 3.0.0
info:
  title: Notification API
  description: Notification service for Nairalink
  version: 1.0.0
servers:
  - url: http://localhost:6000/api/v1/
    description: Send email and sms notification

paths:
  /notification:
    post:
      summary: Send sms notification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  example: Nairalink <support@cloudmendy.tech>
                to:
                  type: string
                  example: customeremail@email.com
                subject:
                  type: string
                  example: Card creation
                html:
                  type: string
                  example: Your Nairalink card has been successfully created
      responses:
        '201':
          description: Created

  # /notification:
  #   post:
  #     summary: Send phone notification.
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               from:
  #                 type: string
  #                 example: Nairalink <support@cloudmendy.tech>
  #               to:
  #                 type: string
  #                 example: customeremail@email.com
  #               subject:
  #                 type: string
  #                 example: Card creation
  #               html:
  #                 type: string
  #                 example: Your Nairalink card has been successfully created
  #     responses:
  #       '201':
  #         description: Created
